name: 'sync-to-tencent-cos'
description: 'sync to tencent cos'
author: 'zhouxhere'
inputs:
  token:
    required: true
    description: 'github token'
    default: ${{ github.token }}
  branch:
    required: true
    description: 'repository branch'
    default: 'main'
  secretId:
    required: true
    description: 'tencent cos secretId'
  secretKey:
    required: true
    description: 'tencent cos secretKey'
  bucket:
    required: true
    description: 'tencent cos bucket'
  region:
    required: true
    description: 'tencent cos region'
  subPath:
    required: true
    description: 'tencent cos sub path'
    default: 'github'
runs:
  using: 'node16'
  main: 'dist/index.js'
